---
expert_execution:
  affinities:
    main_pool_cpus: 2,3,4,5,6,7
    main_pool_pinning: round-robin
    #    ru_timing_cpu: "10"
    #    ofh:
    #      - ru_txrx_cpus: "11"
    #  threads:
    #    main_pool:
    #      nof_threads: 2
    #      task_queue_size: 4096
    #      backoff_period: 0
        #  cell_affinities:
        #    - ru_cpus: "10,11"
        #      ru_pinning: "round-robin"
cu_cp:
  amf:
    addr: 192.168.70.132
    bind_addr: 192.168.70.129
    supported_tracking_areas:
      - tac: 1
        plmn_list:
          - plmn: 00101
            tai_slice_support_list:
              - sst: 1
cell_cfg:
  dl_arfcn: 650000
  common_scs: 30
  band: 78
  plmn: 00101
  tac: 1
  channel_bandwidth_MHz: 20
  ssb:
    ssb_block_power_dbm: -10
  nof_antennas_dl: 1
  nof_antennas_ul: 1
  tdd_ul_dl_cfg:
    dl_ul_tx_period: 10
    nof_dl_slots: 7
    nof_dl_symbols: 6
    nof_ul_slots: 2
    nof_ul_symbols: 4
  prach:
    prach_config_index: 159
    prach_root_sequence_index: 1
    zero_correlation_zone: 0
    prach_frequency_start: 12
  pdsch:
    mcs_table: qam256
ru_ofh:
  ru_bandwidth_MHz: 20
  t1a_min_up: 50
  t1a_max_up: 196
  t1a_min_cp_dl: 258
  t1a_max_cp_dl: 470
  t1a_min_cp_ul: 285
  t1a_max_cp_ul: 429
  ta4_min: 0
  ta4_max: 75
  is_prach_cp_enabled: true
  ignore_ecpri_payload_size: true
  compr_method_ul: bfp
  compr_bitwidth_ul: 9
  compr_method_dl: bfp
  compr_bitwidth_dl: 9
  compr_method_prach: none
  compr_bitwidth_prach: 16
  enable_ul_static_compr_hdr: false
  enable_dl_static_compr_hdr: false
  iq_scaling: 1.0

  cells:
    - network_interface: 0000:01:00.0
      ru_mac_addr: 6c:ad:ad:00:0d:66
      du_mac_addr: 50:7c:6f:02:00:e2
      vlan_tag_up: 2
      vlan_tag_cp: 3
      prach_port_id: [1]
      dl_port_id: [0]
      ul_port_id: [0]

hal:
  eal_args: --lcores 0@8,1@9,2@10,3@11 --main-lcore 0 -a 0000:01:00.0 --socket-mem=4096 --file-prefix=gnb --huge-dir=/mnt/huge
log:
  filename: ./gnb.log
  ofh_level: warning
  all_level: warning
  gtpu_level: warning
  mac_level: warning
